Standardized metadata across profiles
enjoysparkling/signal-mso-fhir-profiles pull request #116
Opened 2023-10-11 07:46 UTC by arunsundar-m

@enjoysparkling I have made the naming convention changes, ran the validation rules across these profiles ( Practitioner and OrganizationAffiliation - A structure must have either differential/snapshot/both). Rest all other issues related are fixed.

2023-10-11 20:31 UTC, enjoysparkling requested changes
Recommend we delete the following resources that have no differentials:
- PractitionerRole
- Practitioner
- OrganizationAffiliation

2023-10-11 20:31 UTC, enjoysparkling commented on input/resources/StructureDefinition-profile-SignalPractitioner.json
```
Message  : Instance failed constraint sdf-6 "A structure must have either a differential, or a snapshot (or both)"
FilePath : input\resources\StructureDefinition-profile-SignalPractitioner.json
Id       : sdf-6
Severity : Error
Context  : StructureDefinition
```

I think we should delete this since we are not making any changes to it.

2023-10-11 20:31 UTC, enjoysparkling commented on input/resources/StructureDefinition-profile-SignalPractitionerRole.json
This one is not throwing an error, but we have not modified it from the [US Core PractitionerRole](http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitionerrole), have we?  I think we should delete it.

2023-10-12 08:42 UTC, arunsundar-m commented on input/resources/StructureDefinition-profile-SignalPractitionerRole.json
We have an element PractitionerRole.specialty added, thats why its not showing up in Forge validation error. I am leaving it as of now.
@enjoysparkling @Gokulsignal

2023-10-12 08:43 UTC, arunsundar-m commented on input/resources/StructureDefinition-profile-SignalOrganizationAffiliation.json
Yes there are no opens issues related to OrganizationAffiliation. I will delete and commit the changes.

2023-10-12 08:47 UTC, arunsundar-m commented
@enjoysparkling I have removed the OrganizationAffiliation and Practitioner profiles. I have excluded PractitionerRole as it has a differential element specialty.

2023-10-12 16:55 UTC, enjoysparkling commented on input/resources/StructureDefinition-profile-SignalPractitionerRole.json
Ok, I see, we replaced the binding in PR https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/48

2023-10-12 17:02 UTC, arunsundar-m commented on input/resources/StructureDefinition-profile-SignalPractitionerRole.json
Do you want to ignore the change and get this deleted?

2023-10-24 20:21 UTC, enjoysparkling approved these changes

2023-10-24 20:43 UTC, merged