Bug fixes for Service Request
enjoysparkling/signal-mso-fhir-profiles pull request #148
Opened 2023-11-08 07:42 UTC by arunsundar-m

2023-11-08 22:30 UTC, enjoysparkling requested changes

2023-11-08 22:30 UTC, enjoysparkling commented on input/resources/StructureDefinition-profile-SignalServiceRequest.json
Remove the differential for .status and .intent, per comments in #148

2023-11-09 06:23 UTC, arunsundar-m commented on input/resources/StructureDefinition-profile-SignalServiceRequest.json
Removed and committed. #https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/148/commits/b439461425d0340c589e198e618a2773cd2e1ff1

2023-11-13 17:10 UTC, enjoysparkling approved these changes

2023-11-13 20:01 UTC, merged