Bugfix/valueset/practitionerrole
enjoysparkling/signal-mso-fhir-profiles pull request #48
Opened 2023-08-14 06:15 UTC by Gokulsignal

@enjoysparkling Hi Matt, Kindly review the pull request.

2023-08-29 00:30 UTC, enjoysparkling requested changes
Changes required:
- Need to bind the HealthcareService NPI Provider Taxonomy to this `PractitionerRole.specialty`.
- Also need to expand the `PractitionerRole.code` value set.

2023-08-29 00:30 UTC, enjoysparkling commented on input/vocabulary/valueset-days-of-week.json
Changes required:
```
Message  : Instance failed constraint vsd-10 "Must have a system if a code is present"
FilePath : input\vocabulary\valueset-days-of-week.json
Id       : vsd-10
Severity : Error
Context  : ValueSet.expansion[0].contains[0]

```

2023-09-13 13:06 UTC, Gokulsignal commented on input/vocabulary/valueset-days-of-week.json
Changes made:
- HealthcareService NPI Provider Taxonomy is binded to this PractitionerRole.specialty.
- 'System' is added to the 'ValueSet.Expansion.Contains' on the input/vocabulary/valueset-days-of-week.json

Kindly review.

2023-09-13 20:00 UTC, merged

2023-09-14 07:54 UTC, Gokulsignal commented on input/vocabulary/valueset-days-of-week.json
Changes Made:

Valueset is created for the practionerRole.code. 

https://github.com/enjoysparkling/signal-mso-fhir-profiles/commit/50c64e9c342b47c8b61384fd921b4b8e076927ab

Kindly review.