Value sets for the Location profile
enjoysparkling/signal-mso-fhir-profiles pull request #50
Opened 2023-08-14 07:09 UTC by Gokulsignal

@enjoysparkling , Hi Matt, Kindly review the pull request.

2023-08-29 00:39 UTC, enjoysparkling requested changes
Changes required:
- Add Location.physicalType
- Add or link (from PractitionerRole) Location.hoursOfOperation.daysOfWeek

2023-08-29 00:39 UTC, enjoysparkling commented on input/vocabulary/valueset-service-delivery-location-role-type.json
Note, we might need to repurpose this for Place of Service (POS), but TBD.

2023-08-29 17:58 UTC, enjoysparkling commented on input/vocabulary/valueset-service-delivery-location-role-type.json
No action needed on this one. Will be addressed by #76.

2023-08-30 16:27 UTC, Gokulsignal commented
Hi @enjoysparkling , 

Added Location.physicalType on the Location profile.

Kindly review.

2023-08-30 22:39 UTC, enjoysparkling approved these changes
Looks good to go.

2023-08-30 22:40 UTC, merged