Value sets for the Simple Observation profile
enjoysparkling/signal-mso-fhir-profiles pull request #51
Opened 2023-08-14 07:20 UTC by Gokulsignal

@enjoysparkling , Hi Matt, Kindly review the pull request.

2023-09-05 17:18 UTC, enjoysparkling requested changes
See comments on files.  
1. Confirm if we need to represent an expansion JSON hierarchy for a few of these
2. add category valueset

2023-09-05 17:18 UTC, enjoysparkling commented on input/vocabulary/valueset-reference-range-applies-to.json
This one is missing the expansion values from the v3-race code system.  Include it, even though this is an example binding.

2023-09-05 17:18 UTC, enjoysparkling commented on input/vocabulary/valueset-reference-range-meaning.json
There is an implicit hierarchy on the http://hl7.org/fhir/R4/valueset-referencerange-meaning.html, but it's not represented here.  If we don't think Devs will use it, we can keep it like this.  
Double-check with UI/Devs to see if they will be using this value set and if they will want the hierarchy for display purposes.

2023-09-05 17:18 UTC, enjoysparkling commented on input/vocabulary/valueset-us-core-simple-observation-category.json
We are missing the category (default) valueset expansion.  Include it here.  
http://hl7.org/fhir/R4/valueset-observation-category.html

2023-09-05 17:18 UTC, enjoysparkling commented on input/vocabulary/valuset-data-absent-reason.json
There is an implicit hierarchy on the http://hl7.org/fhir/R4/valueset-data-absent-reason.html, but it's not represented here. If we don't think Devs will use it, we can keep it like this.
Double-check with UI/Devs to see if they will be using this value set and if they will want the hierarchy for display purposes.

2023-09-05 17:18 UTC, enjoysparkling commented on input/vocabulary/valuset-observation-status.json
There is an implicit hierarchy on the http://hl7.org/fhir/R4/valueset-observation-status.html, but it's not represented here. If we don't think Devs will use it, we can keep it like this.
Double-check with UI/Devs to see if they will be using this value set and if they will want the hierarchy for display purposes.

2023-09-18 11:43 UTC, Gokulsignal commented on input/vocabulary/valueset-reference-range-applies-to.json
Values are expanded from v3-race code system. 

https://github.com/enjoysparkling/signal-mso-fhir-profiles/commit/5d446702f0a9bcf68f2d0aea8812730275b1085b

Kindly review

2023-09-18 15:01 UTC, Gokulsignal commented on input/vocabulary/valueset-reference-range-meaning.json
Checked with Dev team. At this point, there are no requirements in their screens to use this ValueSet. May be there will be requirements at future.

2023-09-18 15:01 UTC, Gokulsignal commented on input/vocabulary/valuset-data-absent-reason.json
Checked with Dev team. At this point, there are no requirements in their screens to use this ValueSet. May be there will be requirements at future.

2023-09-18 15:04 UTC, Gokulsignal commented on input/vocabulary/valuset-observation-status.json
Checked with Dev team. At this point, there are no requirements in their screens to use this ValueSet. May be there will be requirements at future.

2023-09-20 21:40 UTC, enjoysparkling approved these changes

2023-09-20 21:40 UTC, merged