Added Episode of care valuesets
enjoysparkling/signal-mso-fhir-profiles pull request #54
Opened 2023-08-14 07:26 UTC by Gokulsignal

@enjoysparkling , Hi Matt, Kindly review the pull request.

2023-08-28 19:43 UTC, enjoysparkling requested changes
Need System for value set expansion codes

2023-08-28 19:43 UTC, enjoysparkling commented on input/vocabulary/valueset-episode-of-care-type.json
Changes required:
```
Message  : Instance failed constraint vsd-10 "Must have a system if a code is present"
FilePath : input\vocabulary\valueset-episode-of-care-type.json
Id       : vsd-10
Severity : Error
Context  : ValueSet.expansion[0].contains[0]
```
- This should probably represent the Service Type from the HealthcareService resource.  Keep this and include that code system. Recorded in #71
- We may also want to include Program...

2023-08-28 19:43 UTC, enjoysparkling commented on input/vocabulary/valueset-diagnosis-role.json
Changes required:
```
Message  : Instance failed constraint vsd-10 "Must have a system if a code is present"
FilePath : input\vocabulary\valueset-diagnosis-role.json
Id       : vsd-10
Severity : Error
Context  : ValueSet.expansion[0].contains[0]
```

2023-08-30 07:03 UTC, arunsundar-m commented on input/vocabulary/valueset-episode-of-care-type.json
@enjoysparkling Should we ignore this valueset and bind healthcare-service-type valueset here? also we don't get your comment on program?

2023-08-30 08:33 UTC, Gokulsignal commented on input/vocabulary/valueset-diagnosis-role.json
Updated the System to the expansion.contains on valueset-diagnosis-role

2023-08-30 21:44 UTC, enjoysparkling approved these changes
Looks good.

2023-08-30 21:45 UTC, merged