Value sets for the US Core Observation Screening Assessment Profile
enjoysparkling/signal-mso-fhir-profiles pull request #55
Opened 2023-08-14 07:28 UTC by Gokulsignal

@enjoysparkling , Hi Matt, Kindly review the pull request.

2023-09-13 19:57 UTC, enjoysparkling requested changes

2023-09-13 19:57 UTC, enjoysparkling commented on input/vocabulary/us-core-screening-assessment-observation-category.json
Changes required:
```
Message  : Instance count for 'Narrative.div' is 0, which is not within the specified cardinality of 1..1
FilePath : input\vocabulary\us-core-screening-assessment-observation-category.json
Id       : 1028
Severity : Error
Context  : ValueSet.text[0]
```

2023-09-14 10:33 UTC, Gokulsignal commented on input/vocabulary/us-core-screening-assessment-observation-category.json
Removed the following parameters from the "us-core-screening-assessment-observation-category.json"

- TEXT
- META
- VERSION 
- CONTACT

Kindly review.
https://github.com/enjoysparkling/signal-mso-fhir-profiles/commit/807aa19a2f17d79aef7b8821eb00b3a958c3bb1f

2023-09-14 17:09 UTC, enjoysparkling approved these changes

2023-09-14 17:09 UTC, merged