Added valuesets for Service Request
enjoysparkling/signal-mso-fhir-profiles pull request #56
Opened 2023-08-14 07:29 UTC by Gokulsignal

@enjoysparkling , Hi Matt, Kindly review the pull request.

2023-08-28 21:05 UTC, enjoysparkling requested changes
See notes in individual files.

2023-08-28 21:05 UTC, enjoysparkling commented on input/vocabulary/valueset-service-request-order-detail.json
Changes required:
```
Message  : Instance failed constraint vsd-10 "Must have a system if a code is present"
FilePath : input\vocabulary\valueset-service-request-order-detail.json
Id       : vsd-10
Severity : Error
Context  : ValueSet.expansion[0].contains[0]

```

2023-08-28 21:05 UTC, enjoysparkling commented on input/vocabulary/valueset-us-core-service-request-category.json
Changes required:
- We should include the Service Type from HealthcareService in this field, see #72

2023-08-30 09:42 UTC, arunsundar-m commented on input/vocabulary/valueset-us-core-service-request-category.json
@enjoysparkling Should we ignore this value set and bind the valueset-healthcare-service-type to this element in Forge?

2023-08-30 09:43 UTC, arunsundar-m commented on input/vocabulary/valueset-service-request-order-detail.json
@Gokulsignal Can you pick this change?

2023-08-30 10:09 UTC, Gokulsignal commented on input/vocabulary/valueset-service-request-order-detail.json
The 'System' is added to the expansion.contains on 'valueset-service-request-order-detail'

2023-08-30 22:38 UTC, enjoysparkling approved these changes
Looks good to go.

2023-08-30 22:38 UTC, enjoysparkling commented on input/vocabulary/valueset-us-core-service-request-category.json
We'll include this value set, but we will add to it in another task.

2023-08-30 22:38 UTC, merged