Added valuesets for coverage
enjoysparkling/signal-mso-fhir-profiles pull request #57
Opened 2023-08-14 07:30 UTC by Gokulsignal

@enjoysparkling , Hi Matt, Kindly review the pull request.

2023-10-04 17:07 UTC, enjoysparkling requested changes

2023-10-04 17:07 UTC, enjoysparkling commented on input/vocabulary/valueset-coverage-class-code.json
Changes required:
```
Message  : Type checking the data: Encountered unknown element 'definition' at location 'ValueSet.expansion[0].contains[0].definition[0]' while parsing
FilePath : input\vocabulary\valueset-coverage-class-code.json
Id       : 1003
Severity : Error
Context  : ValueSet.expansion[0].contains[0]
```

Also include SYSTEM in the expansion.

2023-10-04 17:07 UTC, enjoysparkling commented on input/vocabulary/valueset-coverage-copay-type-code.json
Changes required:
```
Message  : Instance failed constraint vsd-10 "Must have a system if a code is present"
FilePath : input\vocabulary\valueset-coverage-copay-type-code.json
Id       : vsd-10
Severity : Error
Context  : ValueSet.expansion[0].contains[0]
```

2023-10-04 17:07 UTC, enjoysparkling commented on input/vocabulary/valueset-coverage-financial-exception.json
Changes required:
```
Message  : Instance failed constraint vsd-10 "Must have a system if a code is present"
FilePath : input\vocabulary\valueset-coverage-financial-exception.json
Id       : vsd-10
Severity : Error
Context  : ValueSet.expansion[0].contains[0]
```

2023-10-04 17:07 UTC, enjoysparkling commented on input/vocabulary/valueset-subscriber-relationship.json
Changes required:
```
Message  : Instance failed constraint vsd-10 "Must have a system if a code is present"
FilePath : input\vocabulary\valueset-subscriber-relationship.json
Id       : vsd-10
Severity : Error
Context  : ValueSet.expansion[0].contains[0]
```

2023-10-05 13:06 UTC, Gokulsignal commented
@enjoysparkling , Hi Matt, the above changes are made for the Coverage Value sets. Please review.

2023-10-11 18:56 UTC, enjoysparkling approved these changes

2023-10-11 18:56 UTC, merged